// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/GZ91/linkreduct/internal/models"
)

// HandlerserService is an autogenerated mock type for the HandlerserService type
type HandlerserService struct {
	mock.Mock
}

type HandlerserService_Expecter struct {
	mock *mock.Mock
}

func (_m *HandlerserService) EXPECT() *HandlerserService_Expecter {
	return &HandlerserService_Expecter{mock: &_m.Mock}
}

// AddBatchLink provides a mock function with given fields: _a0, _a1
func (_m *HandlerserService) AddBatchLink(_a0 context.Context, _a1 []string) (map[string]string, error) {
	ret := _m.Called(_a0, _a1)

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]string); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerserService_AddBatchLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBatchLink'
type HandlerserService_AddBatchLink_Call struct {
	*mock.Call
}

// AddBatchLink is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []string
func (_e *HandlerserService_Expecter) AddBatchLink(_a0 interface{}, _a1 interface{}) *HandlerserService_AddBatchLink_Call {
	return &HandlerserService_AddBatchLink_Call{Call: _e.mock.On("AddBatchLink", _a0, _a1)}
}

func (_c *HandlerserService_AddBatchLink_Call) Run(run func(_a0 context.Context, _a1 []string)) *HandlerserService_AddBatchLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *HandlerserService_AddBatchLink_Call) Return(_a0 map[string]string, _a1 error) *HandlerserService_AddBatchLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerserService_AddBatchLink_Call) RunAndReturn(run func(context.Context, []string) (map[string]string, error)) *HandlerserService_AddBatchLink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteToken provides a mock function with given fields: ctx, token
func (_m *HandlerserService) DeleteToken(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandlerserService_DeleteToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteToken'
type HandlerserService_DeleteToken_Call struct {
	*mock.Call
}

// DeleteToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *HandlerserService_Expecter) DeleteToken(ctx interface{}, token interface{}) *HandlerserService_DeleteToken_Call {
	return &HandlerserService_DeleteToken_Call{Call: _e.mock.On("DeleteToken", ctx, token)}
}

func (_c *HandlerserService_DeleteToken_Call) Run(run func(ctx context.Context, token string)) *HandlerserService_DeleteToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *HandlerserService_DeleteToken_Call) Return(_a0 error) *HandlerserService_DeleteToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HandlerserService_DeleteToken_Call) RunAndReturn(run func(context.Context, string) error) *HandlerserService_DeleteToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetServices provides a mock function with given fields: ctx, name
func (_m *HandlerserService) GetServices(ctx context.Context, name string) (map[string]string, error) {
	ret := _m.Called(ctx, name)

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerserService_GetServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServices'
type HandlerserService_GetServices_Call struct {
	*mock.Call
}

// GetServices is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *HandlerserService_Expecter) GetServices(ctx interface{}, name interface{}) *HandlerserService_GetServices_Call {
	return &HandlerserService_GetServices_Call{Call: _e.mock.On("GetServices", ctx, name)}
}

func (_c *HandlerserService_GetServices_Call) Run(run func(ctx context.Context, name string)) *HandlerserService_GetServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *HandlerserService_GetServices_Call) Return(_a0 map[string]string, _a1 error) *HandlerserService_GetServices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerserService_GetServices_Call) RunAndReturn(run func(context.Context, string) (map[string]string, error)) *HandlerserService_GetServices_Call {
	_c.Call.Return(run)
	return _c
}

// GetSmallLink provides a mock function with given fields: _a0, _a1
func (_m *HandlerserService) GetSmallLink(_a0 context.Context, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerserService_GetSmallLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSmallLink'
type HandlerserService_GetSmallLink_Call struct {
	*mock.Call
}

// GetSmallLink is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *HandlerserService_Expecter) GetSmallLink(_a0 interface{}, _a1 interface{}) *HandlerserService_GetSmallLink_Call {
	return &HandlerserService_GetSmallLink_Call{Call: _e.mock.On("GetSmallLink", _a0, _a1)}
}

func (_c *HandlerserService_GetSmallLink_Call) Run(run func(_a0 context.Context, _a1 string)) *HandlerserService_GetSmallLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *HandlerserService_GetSmallLink_Call) Return(_a0 string, _a1 error) *HandlerserService_GetSmallLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerserService_GetSmallLink_Call) RunAndReturn(run func(context.Context, string) (string, error)) *HandlerserService_GetSmallLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokens provides a mock function with given fields: ctx, NameService
func (_m *HandlerserService) GetTokens(ctx context.Context, NameService []string) (map[string]string, error) {
	ret := _m.Called(ctx, NameService)

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]string, error)); ok {
		return rf(ctx, NameService)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]string); ok {
		r0 = rf(ctx, NameService)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, NameService)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerserService_GetTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokens'
type HandlerserService_GetTokens_Call struct {
	*mock.Call
}

// GetTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - NameService []string
func (_e *HandlerserService_Expecter) GetTokens(ctx interface{}, NameService interface{}) *HandlerserService_GetTokens_Call {
	return &HandlerserService_GetTokens_Call{Call: _e.mock.On("GetTokens", ctx, NameService)}
}

func (_c *HandlerserService_GetTokens_Call) Run(run func(ctx context.Context, NameService []string)) *HandlerserService_GetTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *HandlerserService_GetTokens_Call) Return(_a0 map[string]string, _a1 error) *HandlerserService_GetTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerserService_GetTokens_Call) RunAndReturn(run func(context.Context, []string) (map[string]string, error)) *HandlerserService_GetTokens_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function with given fields: _a0, _a1
func (_m *HandlerserService) GetURL(_a0 context.Context, _a1 string) (string, bool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// HandlerserService_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type HandlerserService_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *HandlerserService_Expecter) GetURL(_a0 interface{}, _a1 interface{}) *HandlerserService_GetURL_Call {
	return &HandlerserService_GetURL_Call{Call: _e.mock.On("GetURL", _a0, _a1)}
}

func (_c *HandlerserService_GetURL_Call) Run(run func(_a0 context.Context, _a1 string)) *HandlerserService_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *HandlerserService_GetURL_Call) Return(_a0 string, _a1 bool, _a2 error) *HandlerserService_GetURL_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *HandlerserService_GetURL_Call) RunAndReturn(run func(context.Context, string) (string, bool, error)) *HandlerserService_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLsToken provides a mock function with given fields: _a0, _a1
func (_m *HandlerserService) GetURLsToken(_a0 context.Context, _a1 string) ([]models.ReturnedStructURL, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []models.ReturnedStructURL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.ReturnedStructURL, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.ReturnedStructURL); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ReturnedStructURL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandlerserService_GetURLsToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLsToken'
type HandlerserService_GetURLsToken_Call struct {
	*mock.Call
}

// GetURLsToken is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *HandlerserService_Expecter) GetURLsToken(_a0 interface{}, _a1 interface{}) *HandlerserService_GetURLsToken_Call {
	return &HandlerserService_GetURLsToken_Call{Call: _e.mock.On("GetURLsToken", _a0, _a1)}
}

func (_c *HandlerserService_GetURLsToken_Call) Run(run func(_a0 context.Context, _a1 string)) *HandlerserService_GetURLsToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *HandlerserService_GetURLsToken_Call) Return(_a0 []models.ReturnedStructURL, _a1 error) *HandlerserService_GetURLsToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HandlerserService_GetURLsToken_Call) RunAndReturn(run func(context.Context, string) ([]models.ReturnedStructURL, error)) *HandlerserService_GetURLsToken_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *HandlerserService) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandlerserService_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type HandlerserService_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HandlerserService_Expecter) Ping(ctx interface{}) *HandlerserService_Ping_Call {
	return &HandlerserService_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *HandlerserService_Ping_Call) Run(run func(ctx context.Context)) *HandlerserService_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HandlerserService_Ping_Call) Return(_a0 error) *HandlerserService_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HandlerserService_Ping_Call) RunAndReturn(run func(context.Context) error) *HandlerserService_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewHandlerserService creates a new instance of HandlerserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerserService {
	mock := &HandlerserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
